name: Auto approve

on: 
  pull_request:
    types: [opened, reopened, synchronize, labeled]

jobs:
  assign-reviewers:
    runs-on: ubuntu-latest
    steps:
      - name: Assign two random reviewers
        uses: actions/github-script@v6
        with:
          script: |
            const creator = context.payload.sender.login;
            console.log(creator);
            console.log(context);
