name: Auto Approve & Merge

on: pull_request_target

jobs:
  auto-approve:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write    
    steps:
      - name: Check for a label
        uses: actions/github-script@v3
        id: label-check
        with:
          script: |
            const labels = context.payload.pull_request.labels;
            const labelArray = labels.map(label => label.name);
            const hasLabel = labelArray.includes('auto-merge');
            return hasLabel;    
      - name: Auto approve
        uses: hmarr/auto-approve-action@v3
        if: steps.label-check.outputs.result
        with:
          script: |
            console.info( steps.label-check.outputs.result );
