name: Auto approve

on: 
  pull_request:
    types: [opened, reopened, synchronize, labeled]

jobs:
  assign-reviewers:
    runs-on: ubuntu-latest
    steps:
      - name: Assign two random reviewers
        uses: actions/github-script@v6
        id: get-reviewer
        with:
          script: |
            const creator = context.payload.sender.login;
            const reviewers = context.payload.pull_request.requested_reviewers;
            // console.log(creator);
            // console.log(context);

            // 무작위로 2명 선택
            const shuffled = reviewers.sort(() => 0.5 - Math.random());
            let selectedReviewers = shuffled.slice(0, 2);         

            console.log(selectedReviewers.map(reviewer => reviewer.login).join(','));
            return selectedReviewers.map(reviewer => reviewer.login).join(',');
      - name: Do something if eltriny-bot exists
        if: contains(steps.get-reviewer.outputs.result, 'eltriny-bot')
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.BOT_TOKEN }}
          script: |
            console.info('eltriny-bot step');
            const prNumber = context.payload.pull_request.number;
            await github.rest.pulls.createReview({
              ...context.repo,
              "pull_number": prNumber,
              "event": "APPROVE",
              "body": "Auto Reviews"
            });
      - name: Do something if eltriny-bot exists
        if: contains(steps.get-reviewer.outputs.result, 'eltriny')
        uses: actions/github-script@v6
        with:
          script: |
            console.info('eltriny step');
      - name: Do something if ispiniy exists
        if: contains(steps.get-reviewer.outputs.result, 'ispiniy-dev')
        uses: actions/github-script@v6
        with:
          script: |
            console.info('ispiniy-dev step');            
